# Generated by Django 4.2.2 on 2023-07-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo')),
                ('articulo', models.CharField(max_length=200, verbose_name='Articulo')),
                ('especificaciones', models.TextField(null=True, verbose_name='Especificaciones')),
                ('direccion', models.TextField(null=True, verbose_name='Direccion')),
                ('comentarios', models.TextField(null=True, verbose_name='Comentarios')),
                ('contacto', models.CharField(choices=[('llamada', 'Llamada'), ('whatsapp', 'Whatsapp'), ('correo', 'Correo')], max_length=10, verbose_name='Contacto')),
            ],
        ),
    ]
