# Generated by Django 4.2.2 on 2023-07-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cute_paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='contacto',
            field=models.CharField(blank=True, choices=[('llamada', 'Llamada'), ('whatsapp', 'Whatsapp'), ('correo', 'Correo')], max_length=10, verbose_name='Contacto'),
        ),
    ]
